events { worker_connections 1024; }

http {
  upstream minha_api_cluster {
    server app-node-1:8080 weight=3;
    server app-node-2:8080;
    server app-node-3:8080;
  }

  # Curiosidade de produção: 1 MB consegue armazenar cerca de 16.000 IPs únicos. Com 10 MB, seu lab conseguiria rastrear cerca de 160.000 usuários simultaneamente.
  # rate=2r/s: É o limite de velocidade (Rate). Significa 2 requisições por segundo.
  limit_req_zone $binary_remote_addr zone=meu_limit:10m rate=2r/s;

  server {
    listen 80;

    location / {
      # zone=meu_limite: Diz ao location para usar as regras e o espaço de memória que mapeamos lá em cima.
      # burst=3: Este é o conceito mais importante. O burst funciona como uma fila de espera (ou um buffer). Lembra que o NGINX espera 1 requisição a cada 500ms? Se um usuário legítimo abrir o navegador e carregar sua página, o browser vai disparar várias requisições de uma vez (HTML, CSS, imagens). Sem o burst, o usuário receberia um erro na hora.
      # Com burst=3, o NGINX permite que o usuário "estoure" o limite inicial e coloca até 3 requisições excedentes em uma fila de espera, processando-as de forma cadenciada.
      # nodelay: Por padrão, as requisições que entram na fila do burst ficam paradas esperando o tempo delas (gerando lentidão/delay para o usuário). Quando você adiciona o nodelay, você diz ao NGINX: "Deixe essas 3 requisições extras passarem imediatamente para a API, mas marque-as no histórico como 'slots ocupados' na fila".
      limit_req zone=meu_limit burst=3 nodelay;
      proxy_pass http://minha_api_cluster;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
