events { worker_connections 1024; }

http {
  upstream minha_api_cluster {
    server app-node-1:8080;
    server app-node-2:8080;
    server app-node-3:8080;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://minha_api_cluster;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
